### ISSUE TITLE
bescape/docs/datasets/bescape/input/input.csv

### ISSUE THREAD

**Issue by tkamth** [bedapub/bescape#4]
are there any consequences to the parameters set here in the input file on how the file will be subsequently processed?  

(e.g. currently it's stated as TPM, would it try to convert to cp10k if it's inconsistent with the normalized counts coming from reference scRNASeq dataset?)

**Comment by mirophan** [comment]
The input had some redundant columns. It does not convert TPM to cp10k. I have now updated the file.
